/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dogp.zoocount;

import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * Countpanel holds data for a key on the keyboard. A Key can have a name, a
 * display name, a count and an order.
 *
 * @author jonas
 */
public class CountPanel extends javax.swing.JPanel
implements Comparable<CountPanel>{


    /**
     * Creates new form CountPanel
     *
     * @param character
     * @param value
     */
    public CountPanel(String character, String value) {
        this.smudgifiers = new ArrayList<>();
        initComponents();
        countChar.setText(character);
        this.character = character;
        count.setText(value);
        setOrdering(CountPanel.counter++);
    }

    /**
     * Adds a key listener to all components on the panel
     *
     * @param l
     */
    @Override
    public void addKeyListener(KeyListener l) {
        super.addKeyListener(l);
        countChar.addKeyListener(l);
        count.addKeyListener(l);
        settingsButton.addKeyListener(l);
        shortNameLabel.addKeyListener(l);
        jPanel1.addKeyListener(l);
        jPanel2.addKeyListener(l);
    }

    /**
     * Get the count value
     *
     * @return the current value
     */
    public String getValue() {
        return count.getText();
    }

    /**
     * Set the count value
     *
     * @param s the value to set
     */
    public void setValue(String s) {
        count.setText(s);
    }

    /**
     * Get the character key
     *
     * @return the character key
     */
    public String getChar() {
        return character;
    }

    /**
     * Get the full name of the character
     *
     * @return full name
     */
    public String getCharName() {
        return name;
    }

    /**
     * Get the short name / display name of the character
     *
     * @return the short name
     */
    public String getCharShortName() {
        return shortname;
    }

    /**
     * Set the character key
     *
     * @param s the character key
     */
    public void setChar(String s) {
        character = s;
    }

    /**
     * Set the character name. This is displayed on hover.
     *
     * @param s character name
     */
    public void setCharName(String s) {
        name = s;
        shortNameLabel.setToolTipText(s);
    }

    /**
     * Set the character short name, displayed on the UI
     *
     * @param s the short name
     */
    public void setCharShortName(String s) {
        shortname = s;
        if ("".equals(s)) {
            shortNameLabel.setText("");
        }
        else {
            shortNameLabel.setText(s + ": ");
        }
    }

    /**
     * Get the ordering of this panel, used to order the output and the panels
     * in the UI
     *
     * @return the ordering
     */
    public int getOrdering() {
        return ordering;
    }

    /**
     * Set the ordering number for this panel. This defines the order when data
     * is exported to file.
     *
     * @param ordering the ordering to set
     */
    public void setOrdering(int ordering) {
        this.ordering = ordering;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        shortNameLabel = new javax.swing.JLabel();
        countChar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        count = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.BorderLayout());

        jPanel1.add(shortNameLabel);

        countChar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countChar.setText("A");
        jPanel1.add(countChar);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");
        jPanel2.add(count);

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dogp/zoocount/resources/settings.png"))); // NOI18N
        settingsButton.setFocusable(false);
        settingsButton.setRequestFocusEnabled(false);
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(settingsButton);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        JTextField name = new JTextField(getCharName());
        JTextField shortname = new JTextField(getCharShortName());
        JComponent[] input = new JComponent[] {
            new JLabel("Data name"),
            name,
            new JLabel("Display name (short)"),
            shortname
        };
        int result = JOptionPane.showConfirmDialog(this, input);
        if (result == JOptionPane.OK_OPTION) {
            if(
                name.getText().trim().length() > 0 ||
                shortname.getText().trim().length() > 0
            ) {
                fireSmudge(true);
            }
            setCharName(name.getText().trim());
            setCharShortName(shortname.getText().trim());
        }
    }//GEN-LAST:event_settingsButtonActionPerformed

    private String name = "";
    private String shortname = "";
    private String character = "";
    private int ordering = 0;
    private static int counter = 0;
    private ArrayList<Smudgifier> smudgifiers;

    /**
     * Overrides toString, returning a csv string
     *
     * @return "character","shortname","name","count"
     */
    @Override
    public String toString() {
        StringBuilder output = new StringBuilder();
        String separator = Settings.getInstance().getOption(
            "csv.separator", ","
        );
        String quote = Settings.getInstance().getOption(
            "csv.quote", "\""
        );

        String[] strings= new String[] {
            quote,
            character,
            quote,
            separator,
            quote,
            shortname,
            quote,
            separator,
            quote,
            name,
            quote,
            separator,
            count.getText(),
        };
        for (String s : strings) {
            output.append(s);
        }
        return output.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel count;
    private javax.swing.JLabel countChar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel shortNameLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Used when comparing panels against each other, for sorting
     *
     * @param o
     * @return
     */
    @Override
    public int compareTo(CountPanel o) {
        return this.getOrdering() - o.getOrdering();
    }

    /**
     * Reset the count for this panel
     */
    public void clearCounts() {
        count.setText("0");
    }

    /**
     * Reset the names for this panel to an empty string
     */
    public void clearNames() {
        shortNameLabel.setText("");
        shortNameLabel.setToolTipText("");
        shortname = "";
        name = "";
    }

    /**
     * Add a smudgifier to notify if this panel has been smudged
     *
     * @param s
     */
    public void addSmudgifier(Smudgifier s) {
        smudgifiers.add(s);
    }

    /**
     * Remove a smugifier from this panels list of smugifiers
     *
     * @param s
     */
    public void removeSmudgifier(Smudgifier s) {
        smudgifiers.remove(s);
    }

    /**
     * Notify smugifiers some value in this panel has changed.
     *
     * @param dirty
     */
    private void fireSmudge(boolean dirty) {
        for (Smudgifier s : smudgifiers) {
            s.smudge(dirty);
        }
    }
}
