/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dogp.zoocount;

import java.awt.event.KeyListener;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jonas
 */
public class CountPanel extends javax.swing.JPanel
implements Comparable<CountPanel>{


    /**
     * Creates new form CountPanel
     * @param text
     * @param value
     */
    public CountPanel(String text, String value) {
        initComponents();
        countChar.setText(text);
        character = text;
        count.setText(value);
        setOrdering(CountPanel.counter++);
    }

    @Override
    public void addKeyListener(KeyListener l) {
        super.addKeyListener(l);
        countChar.addKeyListener(l);
        count.addKeyListener(l);
        settingsButton.addKeyListener(l);
        shortNameLabel.addKeyListener(l);
        jPanel1.addKeyListener(l);
        jPanel2.addKeyListener(l);
    }
    public String getValue() {
        return count.getText();
    }
    public void setValue(String s) {
        count.setText(s);
    }
    public String getChar() {
        return character;
    }
    public String getCharName() {
        return name;
    }
    public String getCharShortName() {
        return shortname;
    }
    public void setChar(String s) {
        character = s;
    }
    public void setCharName(String s) {
        name = s;
        shortNameLabel.setToolTipText(s);
    }
    public void setCharShortName(String s) {
        shortname = s;
        if ("".equals(s)) {
            shortNameLabel.setText("");
        }
        else {
            shortNameLabel.setText(s + ": ");
        }
    }
   /**
     * @return the ordering
     */
    public int getOrdering() {
        return ordering;
    }

    /**
     * @param ordering the ordering to set
     */
    public void setOrdering(int ordering) {
        this.ordering = ordering;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        shortNameLabel = new javax.swing.JLabel();
        countChar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        count = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.BorderLayout());

        jPanel1.add(shortNameLabel);

        countChar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countChar.setText("A");
        jPanel1.add(countChar);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");
        jPanel2.add(count);

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dogp/zoocount/resources/settings.png"))); // NOI18N
        settingsButton.setFocusable(false);
        settingsButton.setRequestFocusEnabled(false);
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(settingsButton);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        JTextField name = new JTextField(getCharName());
        JTextField shortname = new JTextField(getCharShortName());
        JComponent[] input = new JComponent[] {
            new JLabel("Data name"),
            name,
            new JLabel("Display name (short)"),
            shortname
        };
        int result = JOptionPane.showConfirmDialog(this, input);
        if (result == JOptionPane.OK_OPTION) {
            setCharName(name.getText().trim());
            setCharShortName(shortname.getText().trim());
        }
    }//GEN-LAST:event_settingsButtonActionPerformed

    private String name = "";
    private String shortname = "";
    private String character = "";
    private int ordering = 0;
    private static int counter = 0;

    @Override
    public String toString() {
        StringBuilder output = new StringBuilder();
        String separator = Settings.getInstance().getOption(
            "csv.separator", ","
        );
        String quote = Settings.getInstance().getOption(
            "csv.quote", "\""
        );

        String[] strings= new String[] {
            quote,
            character,
            quote,
            separator,
            quote,
            shortname,
            quote,
            separator,
            quote,
            name,
            quote,
            separator,
            count.getText(),
        };
        for (String s : strings) {
            output.append(s);
        }
        return output.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel count;
    private javax.swing.JLabel countChar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel shortNameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public int compareTo(CountPanel o) {
        return this.getOrdering() - o.getOrdering();
    }

    public void clearCounts() {
        count.setText("0");
    }
    public void clearNames() {
        shortNameLabel.setText("");
        shortNameLabel.setToolTipText("");
        shortname = "";
        name = "";
    }
}
