/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dogp.zoocount;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileFilter;
import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author jonas
 */
public class MainFrame extends javax.swing.JFrame implements KeyListener{

    private final HashMap<String, CountPanel> data = new HashMap(); 
    private String file = null;
    /**
     * Creates new form MainFrame
     */
    private MainFrame() {
        initComponents();
        moreComponents();
        initSettings();
    }
    private void moreComponents(){
        jPanel2.setLayout(new GridLayout(7, 9, 3, 3));
        // Numbers 0-9
        for (int i=0; i<10; i++) {
            addPanel(Integer.toString(i));
        }
        // Capital letters A-Z
        for (int i=65; i<91; i++) {
            addPanel(Character.toString((char)i));
        }
        // Lowercase letters a-z
        for (int i=97; i<123; i++) {
            addPanel(Character.toString((char)i));
        }
        // ...and the spacebar
        addPanel("_");
        this.addKeyListener(this);
        jPanel1.addKeyListener(this);
        jPanel2.addKeyListener(this);
        countHistory.addKeyListener(this);
    }
    
    private void addPanel(String key){
        CountPanel value;
        if ("_".equals(key)) {
            key = "_";
        }
        value = new CountPanel(key, 0);
        value.addKeyListener(this);
        value.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        data.put(key, value);
        jPanel2.add(value);
    }
    
   private static MainFrame main;

    public static synchronized MainFrame getInstance() {
        if (main == null)
            main=new MainFrame();
        return main;
    }

    /**
     *
     */
    public void reveal() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        countHistory = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveMenu = new javax.swing.JMenuItem();
        loadMenu = new javax.swing.JMenuItem();
        preferencesMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        fullscreenMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 750));

        jPanel3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout(10, 30));

        title.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Start counting");
        jPanel1.add(title, java.awt.BorderLayout.NORTH);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        countHistory.setEditable(false);
        jScrollPane2.setViewportView(countHistory);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel1, java.awt.BorderLayout.NORTH);

        jMenu1.setText("File");

        saveMenu.setText("Save");
        saveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenu);

        loadMenu.setText("Open");
        loadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuActionPerformed(evt);
            }
        });
        jMenu1.add(loadMenu);

        preferencesMenu.setText("Preferences...");
        preferencesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesMenuActionPerformed(evt);
            }
        });
        jMenu1.add(preferencesMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        fullscreenMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        fullscreenMenu.setText("Fullscreen");
        fullscreenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullscreenMenuActionPerformed(evt);
            }
        });
        jMenu3.add(fullscreenMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preferencesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencesMenuActionPerformed
        JTextArea text = new JTextArea();
        text.setText(Settings.getInstance().toString());
        JComponent[] input = new JComponent[] {
            new JLabel("Preferences"),
            text,
        };
        int result = JOptionPane.showConfirmDialog(this, input);
        if (result == JOptionPane.OK_OPTION) {
            Settings.getInstance().importPreferences(text.getText());
        }

    }//GEN-LAST:event_preferencesMenuActionPerformed

    private void loadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadMenuActionPerformed

    private void saveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuActionPerformed
        try {
            if (this.file == null) {
                JFileChooser fc = new JFileChooser();
                fc.setAcceptAllFileFilterUsed(false);
                fc.setFileFilter(new FileFilter() {
                    @Override
                    public boolean accept(File f) {
                        return f.getName().endsWith(".xlsx");
                    }

                    @Override
                    public String getDescription() {
                        return "Excel spreadsheet files (.xlsx)";
                    }
                });
                int i = fc.showSaveDialog(main);
                if (i == JFileChooser.CANCEL_OPTION) {
                    return;
                }
                else {
                    this.file = fc.getSelectedFile().getName();
                    if (!this.file.endsWith(".xlsx")) {
                        this.file += ".xlsx";
                    }
                }
            }
            Workbook wb = new HSSFWorkbook();
            Sheet s = wb.createSheet("Data");

            List<CountPanel> list = new ArrayList<>(data.values());
            Collections.sort(list);
            Iterator<CountPanel> iter = list.iterator();
            boolean all = Boolean.parseBoolean(
                Settings.getInstance().getOption("general.saveAllValues")
            );
            int row = 0;
            Row r = s.createRow(row++);
            r.createCell(0).setCellValue("Name");
            r.createCell(1).setCellValue("Short name");
            r.createCell(2).setCellValue("Character");
            r.createCell(3).setCellValue("Count");

            for (int i=0; i<list.size(); i++) {
                CountPanel p = list.get(i);
                if (!all && "0".equals(p.getValue())) {
                    continue;
                }
                r = s.createRow(row++);
                r.createCell(0).setCellValue(p.getCharName());
                r.createCell(1).setCellValue(p.getCharShortName());
                r.createCell(2).setCellValue(p.getChar());
                r.createCell(3).setCellValue(p.getValue());
            }
            OutputStream out = new FileOutputStream(file);
            wb.write(out);
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (EncryptedDocumentException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveMenuActionPerformed

    private void fullscreenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullscreenMenuActionPerformed
        toggleFullscreen(JFrame.MAXIMIZED_BOTH == this.getExtendedState());
    }//GEN-LAST:event_fullscreenMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void toggleFullscreen(boolean isFullscreen) {
        if (isFullscreen) {
            this.setExtendedState(JFrame.NORMAL);
        }
        else {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane countHistory;
    private javax.swing.JMenuItem fullscreenMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadMenu;
    private javax.swing.JMenuItem preferencesMenu;
    private javax.swing.JMenuItem saveMenu;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

   @Override
    public void keyTyped(KeyEvent e) {
        e.consume();
        String s = Character.toString(e.getKeyChar());
        if(" ".equals(s)) s = "_";
        CountPanel p = data.get(s);
        if (p == null) return;
        countHistory.setText(countHistory.getText() + s);
        int value;
        try {
            value = Integer.parseInt(p.getValue());
        } catch (Exception ex){
            value = 0;
        }
        p.setValue(Integer.toString(++value));
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            String s = countHistory.getText();
            if (s.length() >0) {
                String r = s.substring(s.length()-1, s.length());
                s = s.substring(0, s.length()-1);
                countHistory.setText(s);
                if("_".equals(r)) r = " ";
                CountPanel p = data.get(r);
                if (p == null) return;
                int value;
                try {
                    value = Integer.parseInt(p.getValue());
                    p.setValue(Integer.toString(--value));
                } catch (Exception ex){
                    p.setValue("0");
                }
            }
        }
        e.consume();
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    private void initSettings() {
        Settings s = Settings.getInstance();
        if ("".equals(s.getOption("csv.separator"))) {
            s.setOption("csv.separator", ",");
        }
        if ("".equals(s.getOption("csv.quote"))) {
            s.setOption("csv.quote", "\"");
        }
        if (Boolean.parseBoolean(s.getOption("isFullscreen", "false"))) {
            toggleFullscreen(false);
        }
        else {
            s.setOption("isFullscreen", "false");
        }
    }
}
